### ISSUE TITLE
QGIS en Agència Catalana de l'Aigua

### ISSUE THREAD

**Issue by dcastellvell** [sigdeletras/qgis-case-studies#4]
En relación a la petición de actualizar el listado de entidades públicas que usan QGIS, en la “Agència Catalana de l'Aigua” hemos publicado, en el marco de las normas de redacción de los proyectos para la ejecución de las actuaciones de ésta agencia, en formato QGIS, un modelo de datos SIG de saneamiento y un modelo de datos SIG de expropiaciones. 
Están disponibles en:  https://aca.gencat.cat/ca/laca/perfil-del-contractant/normes-de-redaccio-de-projectes/

**Comment by sigdeletras** [comment]
Muchas gracias @dcastellvell. Actualizo repositorio con la información

**Comment by sigdeletras** [comment]
Commit realizado https://github.com/sigdeletras/qgis-case-studies/commit/ae61d4666d13f00d47eae8fd5702b95e2d927c03

**Comment by sigdeletras** [comment]
Commit realizado https://github.com/sigdeletras/qgis-case-studies/commit/ae61d4666d13f00d47eae8fd5702b95e2d927c03
